# Generated by Django 5.2.8 on 2026-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
