# Generated by Django 5.2.8 on 2026-04-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0008_category_petition_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetitionAttachment',
        ),
    ]
