# Generated by Django 5.2.8 on 2026-04-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_delete_petitionattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='alias',
        ),
    ]
