# Generated by Django 5.2.8 on 2025-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_followup_notes_petition_followup_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='promo/')),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha')], default='right', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
