# Generated by Django 5.2.8 on 2025-11-25 08:47

import petitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_promocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocontent',
            name='file',
            field=models.FileField(upload_to='promo/', validators=[petitions.models.PromoContent.validate_promo_file]),
        ),
    ]
