# Generated by Django 5.2.8 on 2025-11-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='attachments/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petitions.petition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('petition', 'order')},
            },
        ),
    ]
