# Generated by Django 5.2.8 on 2025-11-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_comment_alias_userprofile_show_petitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alias',
        ),
    ]
